apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchanger-deployment
  labels:
    app: currency-exchanger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchanger
  template:
    metadata:
      labels:
        app: currency-exchanger
    spec:
      containers:
      - name: currencyexchanger
        image: uchamod/currency-exchanger:2
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
