apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchanger-deployment
  labels:
    app: currency-exchanger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-exchanger
  template:
    metadata:
      labels:
        app: currency-exchanger
    spec:
      containers:
      - name: currencyexchanger
        image: uchamod/currency-exchanger:2
        ports:
        - containerPort: 5000
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: api-key


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: currency-exchanger
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
