apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: currencyexchanger
        image: uchamod/currency_react_i:v3
        ports:
        - containerPort: 3000
    # env:
    #   - name: BACKEND_URL
    #     valueFrom:
    #       configMapKeyRef:
    #         name: backend-config
    #         key: backend-url
    
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
